### ISSUE TITLE
WebAssembly Studio not works yet?

### ISSUE THREAD

**Issue by MaxGraey** [esmbly/esmbly#25]
## Summary

I tried this link:
https://esmbly.github.io/WebAssemblyStudio/

push `Build` button and nothing happened.

**Comment by ollelauribostrom** [comment]
Thanks for reporting! 

Both Esmbly examples are working for me (Chrome 74). Are you getting any errors in the console?

**Comment by MaxGraey** [comment]
Nope, any errors. I runned on Firefox 66 btw

**Comment by ollelauribostrom** [comment]
Should be fixed now, if you want to give it a try @MaxGraey 🙂

**Comment by MaxGraey** [comment]
thanks!
